spring.application.name=biblioteca-backend
spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]
server.port=8080
app.cors.allowed-origins=http://localhost:4200

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml



spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/biblioteca}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-minutes=${APP_JWT_EXPIRATION_MINUTES:60}

app.admin.username=${APP_ADMIN_USERNAME:}
app.admin.password=${APP_ADMIN_PASSWORD:}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/la-biblioteca}
spring.security.oauth2.resourceserver.jwt.audiences[0]=${KEYCLOAK_AUDIENCE:biblioteca-api}