spring.application.name=biblioteca-backend
spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]
server.port=8080
app.cors.allowed-origins=http://localhost:4200

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml



spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/biblioteca}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-minutes=${APP_JWT_EXPIRATION_MINUTES:60}
